-- SanVaCau - PostgreSQL 17 - Simplified
-- Chạy file này trong database sanvacau bằng pgAdmin Query Tool.
-- Có Category.parent_id để hỗ trợ danh mục cha/con.
-- Không gồm OTP, Tournament, Promotion, Member Point, đặt dịch vụ vợt.

BEGIN;

-- 1. BRANCH: Chi nhánh/cơ sở Sân&Cầu
CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Mã chi nhánh
    name VARCHAR(150) NOT NULL,                             -- Tên chi nhánh
    address VARCHAR(300) NOT NULL,                          -- Địa chỉ
    phone VARCHAR(20),                                      -- Số điện thoại
    opening_time TIME NOT NULL,                             -- Giờ mở cửa
    closing_time TIME NOT NULL,                             -- Giờ đóng cửa
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',           -- ACTIVE/INACTIVE
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,-- Ngày tạo
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,-- Ngày cập nhật
    CONSTRAINT ck_branch_status CHECK (status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT ck_branch_hours CHECK (opening_time < closing_time)
);

-- 2. APP_USER: Tài khoản người dùng
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Mã người dùng
    email VARCHAR(255) NOT NULL UNIQUE,                     -- Email đăng nhập
    password_hash VARCHAR(255) NOT NULL,                    -- Mật khẩu đã băm
    full_name VARCHAR(150) NOT NULL,                        -- Họ tên
    phone VARCHAR(20),                                      -- Số điện thoại
    role VARCHAR(30) NOT NULL DEFAULT 'CUSTOMER',           -- Vai trò
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',           -- Trạng thái
    branch_id BIGINT,                                       -- Chi nhánh làm việc
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,    -- Có bắt đổi mật khẩu
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    CHECK (role IN ('CUSTOMER','STAFF','BRANCH_MANAGER','ADMIN')),
    CHECK (status IN ('ACTIVE','LOCKED','INACTIVE')),
    CHECK (
      (role IN ('STAFF','BRANCH_MANAGER') AND branch_id IS NOT NULL)
      OR (role IN ('CUSTOMER','ADMIN') AND branch_id IS NULL)
    )
);

-- 3. CATEGORY: Danh mục sản phẩm, hỗ trợ cha/con
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Mã danh mục
    name VARCHAR(120) NOT NULL,                             -- Tên danh mục
    parent_id BIGINT,                                       -- ID danh mục cha; NULL = danh mục gốc
    description VARCHAR(500),                               -- Mô tả
    sort_order INT NOT NULL DEFAULT 0,                      -- Thứ tự hiển thị
    is_active BOOLEAN NOT NULL DEFAULT TRUE,                -- Đang sử dụng?
    FOREIGN KEY (parent_id) REFERENCES category(id),
    CHECK (parent_id IS NULL OR parent_id <> id)
);

-- 4. BRAND: Thương hiệu
CREATE TABLE brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,                      -- Yonex, Victor...
    description VARCHAR(500),                               -- Mô tả
    is_active BOOLEAN NOT NULL DEFAULT TRUE                 -- Trạng thái
);

-- 5. PRODUCT: Sản phẩm
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,                            -- Danh mục
    brand_id BIGINT,                                        -- Thương hiệu
    name VARCHAR(200) NOT NULL,                             -- Tên sản phẩm
    description TEXT,                                       -- Mô tả chi tiết
    image_url VARCHAR(1000),                                -- Ảnh đại diện
    is_active BOOLEAN NOT NULL DEFAULT TRUE,                -- Đang kinh doanh?
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (brand_id) REFERENCES brand(id)
);

-- 6. PRODUCT_VARIANT: Biến thể sản phẩm
CREATE TABLE product_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,                             -- Sản phẩm gốc
    sku VARCHAR(80) NOT NULL UNIQUE,                        -- Mã SKU
    variant_name VARCHAR(150) NOT NULL,                     -- Ví dụ 4U5, Size 42
    price NUMERIC(18,2) NOT NULL CHECK (price >= 0),        -- Giá
    image_url VARCHAR(1000),                                -- Ảnh biến thể
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (product_id) REFERENCES product(id)
);

-- 7. INVENTORY: Tồn kho biến thể theo chi nhánh
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,                              -- Chi nhánh
    product_variant_id BIGINT NOT NULL,                     -- Biến thể
    quantity INT NOT NULL DEFAULT 0 CHECK (quantity >= 0),  -- Số lượng
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (branch_id, product_variant_id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
);

-- 8. CART: Giỏ hàng, mỗi khách một giỏ
CREATE TABLE cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL UNIQUE,                     -- Khách hàng
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES app_user(id)
);

-- 9. CART_ITEM: Các món trong giỏ
CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,                                -- Giỏ
    product_variant_id BIGINT NOT NULL,                     -- Biến thể
    quantity INT NOT NULL CHECK (quantity > 0),             -- Số lượng
    UNIQUE (cart_id, product_variant_id),
    FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
    FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
);

-- 10. CUSTOMER_ORDER: Đơn mua hàng nhận tại chi nhánh
CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,                            -- Người mua
    branch_id BIGINT NOT NULL,                              -- Nơi nhận hàng
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',          -- Trạng thái
    total_amount NUMERIC(18,2) NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_at TIMESTAMP,                                     -- Sẵn sàng nhận
    completed_at TIMESTAMP,                                 -- Đã nhận
    cancelled_at TIMESTAMP,                                 -- Đã hủy
    FOREIGN KEY (customer_id) REFERENCES app_user(id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    CHECK (status IN ('PENDING','READY_FOR_PICKUP','COMPLETED','CANCELLED'))
);

-- 11. ORDER_ITEM: Chi tiết đơn hàng
CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,                               -- Đơn hàng
    product_variant_id BIGINT NOT NULL,                     -- Biến thể mua
    product_name VARCHAR(200) NOT NULL,                     -- Snapshot tên sản phẩm
    variant_name VARCHAR(150) NOT NULL,                     -- Snapshot biến thể
    unit_price NUMERIC(18,2) NOT NULL CHECK (unit_price >= 0),
    quantity INT NOT NULL CHECK (quantity > 0),
    FOREIGN KEY (order_id) REFERENCES customer_order(id),
    FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
);

-- 12. COURT: Từng sân cầu lông trong chi nhánh
CREATE TABLE court (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,                              -- Chi nhánh
    name VARCHAR(100) NOT NULL,                             -- Sân 1, Sân 2...
    description VARCHAR(500),                               -- Mô tả
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',           -- Trạng thái
    UNIQUE (branch_id, name),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    CHECK (status IN ('ACTIVE','MAINTENANCE','INACTIVE'))
);

-- 13. TIME_SLOT: Khung giờ đặt sân dùng chung
CREATE TABLE time_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIME NOT NULL,                               -- Bắt đầu
    end_time TIME NOT NULL,                                 -- Kết thúc
    sort_order INT NOT NULL UNIQUE,                         -- Thứ tự
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (start_time, end_time),
    CHECK (start_time < end_time)
);

-- 14. COURT_PRICE: Giá từng sân theo khung giờ
CREATE TABLE court_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    court_id BIGINT NOT NULL,                               -- Sân
    time_slot_id BIGINT NOT NULL,                           -- Khung giờ
    price NUMERIC(18,2) NOT NULL CHECK (price >= 0),        -- Giá
    UNIQUE (court_id, time_slot_id),
    FOREIGN KEY (court_id) REFERENCES court(id),
    FOREIGN KEY (time_slot_id) REFERENCES time_slot(id)
);

-- 15. BOOKING: Phiếu đặt sân
CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,                            -- Người đặt
    court_id BIGINT NOT NULL,                               -- Sân
    booking_date DATE NOT NULL,                             -- Ngày chơi
    status VARCHAR(20) NOT NULL DEFAULT 'BOOKED',           -- Trạng thái
    total_amount NUMERIC(18,2) NOT NULL CHECK (total_amount >= 0),
    payment_method VARCHAR(20),                             -- CASH/BANK_TRANSFER/MOCK_ONLINE
    payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',   -- UNPAID/PAID
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checked_in_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES app_user(id),
    FOREIGN KEY (court_id) REFERENCES court(id),
    CHECK (status IN ('BOOKED','CHECKED_IN','COMPLETED','CANCELLED')),
    CHECK (payment_method IS NULL OR payment_method IN ('CASH','BANK_TRANSFER','MOCK_ONLINE')),
    CHECK (payment_status IN ('UNPAID','PAID'))
);

-- 16. BOOKING_SLOT: Các slot giờ thuộc một booking
CREATE TABLE booking_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,                             -- Phiếu đặt
    court_id BIGINT NOT NULL,                               -- Sân
    booking_date DATE NOT NULL,                             -- Ngày
    time_slot_id BIGINT NOT NULL,                           -- Slot giờ
    price_at_booking NUMERIC(18,2) NOT NULL CHECK (price_at_booking >= 0),
    UNIQUE (booking_id, time_slot_id),
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE,
    FOREIGN KEY (court_id) REFERENCES court(id),
    FOREIGN KEY (time_slot_id) REFERENCES time_slot(id)
);

-- 17. RACKET_SERVICE: Danh mục dịch vụ vợt, chỉ để giới thiệu
CREATE TABLE racket_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,                             -- Tên dịch vụ
    description VARCHAR(1000),                              -- Mô tả
    image_url VARCHAR(1000),                                -- Ảnh
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 18. BRANCH_SERVICE: Dịch vụ được giới thiệu tại từng chi nhánh
CREATE TABLE branch_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,                              -- Chi nhánh
    service_id BIGINT NOT NULL,                             -- Dịch vụ
    reference_price NUMERIC(18,2) CHECK (reference_price IS NULL OR reference_price >= 0),
    description VARCHAR(1000),                              -- Mô tả riêng
    estimated_duration VARCHAR(100),                        -- Thời gian tham khảo
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (branch_id, service_id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (service_id) REFERENCES racket_service(id)
);

-- 19. NEWS: Tin tức
CREATE TABLE news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(250) NOT NULL,                            -- Tiêu đề
    summary VARCHAR(500),                                   -- Tóm tắt
    content TEXT NOT NULL,                                  -- Nội dung
    thumbnail_url VARCHAR(1000),                            -- Ảnh
    author_user_id BIGINT NOT NULL,                         -- Người đăng
    branch_id BIGINT,                                       -- NULL = tin chung
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',            -- DRAFT/PUBLISHED/HIDDEN
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_user_id) REFERENCES app_user(id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    CHECK (status IN ('DRAFT','PUBLISHED','HIDDEN'))
);

-- 20. BANNER: Slide/Banner trang chủ
CREATE TABLE banner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),                                     -- Tiêu đề
    image_url VARCHAR(1000) NOT NULL,                       -- Ảnh banner
    link_url VARCHAR(1000),                                 -- Link khi bấm
    sort_order INT NOT NULL DEFAULT 0,                      -- Thứ tự
    start_at TIMESTAMP,                                     -- Bắt đầu hiển thị
    end_at TIMESTAMP,                                       -- Kết thúc hiển thị
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (start_at IS NULL OR end_at IS NULL OR start_at < end_at)
);

-- 21. AUDIT_LOG: Nhật ký thao tác quản trị
CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,                                -- Người thao tác
    action VARCHAR(100) NOT NULL,                           -- Hành động
    entity_type VARCHAR(100) NOT NULL,                      -- Loại dữ liệu
    entity_id BIGINT,                                       -- ID dữ liệu
    description VARCHAR(1000),                              -- Nội dung
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES app_user(id)
);

-- Index
CREATE INDEX ix_app_user_branch ON app_user(branch_id, role);
CREATE INDEX ix_product_category ON product(category_id);
CREATE INDEX ix_product_brand ON product(brand_id);
CREATE INDEX ix_inventory_branch ON inventory(branch_id);
CREATE INDEX ix_order_customer ON customer_order(customer_id, created_at);
CREATE INDEX ix_order_branch_status ON customer_order(branch_id, status);
CREATE INDEX ix_booking_customer_date ON booking(customer_id, booking_date);
CREATE INDEX ix_booking_court_date ON booking(court_id, booking_date);
CREATE INDEX ix_booking_slot_schedule ON booking_slot(court_id, booking_date, time_slot_id);
CREATE INDEX ix_news_status_published ON news(status, published_at);

-- Khung giờ mặc định 60 phút, 06:00-22:00
INSERT INTO time_slot (start_time, end_time, sort_order) VALUES
('06:00','07:00',1), ('07:00','08:00',2), ('08:00','09:00',3),
('09:00','10:00',4), ('10:00','11:00',5), ('11:00','12:00',6),
('12:00','13:00',7), ('13:00','14:00',8), ('14:00','15:00',9),
('15:00','16:00',10), ('16:00','17:00',11), ('17:00','18:00',12),
('18:00','19:00',13), ('19:00','20:00',14), ('20:00','21:00',15),
('21:00','22:00',16);

COMMIT;

-- Lưu ý nghiệp vụ:
-- Backend phải kiểm tra các BookingSlot được chọn là liên tiếp.
-- Backend phải ngăn hai booking đang hoạt động chiếm cùng court + date + time_slot.
-- Booking CANCELLED không còn chiếm slot.
-- Cart không giữ tồn kho; tạo Order mới kiểm tra/trừ tồn kho trong transaction.
