USE SanVaCau;
GO

-- ======================= BRANDS =======================
INSERT INTO dbo.Brand (Name, Description, IsActive) VALUES (N'Yonex', N'Thương hiệu Yonex', 1);
INSERT INTO dbo.Brand (Name, Description, IsActive) VALUES (N'Lining', N'Thương hiệu Lining', 1);
INSERT INTO dbo.Brand (Name, Description, IsActive) VALUES (N'Victor', N'Thương hiệu Victor', 1);
GO

-- ===================== CATEGORIES =====================
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (NULL, N'Vợt cầu lông', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (NULL, N'Giày cầu lông', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (NULL, N'Áo cầu lông', NULL, 1);
GO

INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (1, N'Vợt cầu lông Yonex', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (1, N'Vợt cầu lông Lining', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (2, N'Giày cầu lông Yonex', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (2, N'Giày cầu lông Victor', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (3, N'Áo cầu lông Yonex', NULL, 1);
INSERT INTO dbo.Category (ParentId, Name, Description, IsActive) VALUES (3, N'Áo cầu lông Lining', NULL, 1);
GO

-- ===================== PRODUCTS =======================
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (4, 1, N'Vợt Cầu LôngVợt cầu lông YonexVợt cầu lông VictorVợt cầu lông LiningVợt Cầu Lông VSVợt Cầu Lông MizunoVợt cầu lông ApacsVợt Cầu Lông VNBVợt cầu lông ProaceVợt cầu lông ForzaVợt Cầu Lông FlyPowerXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (1, 'YON-00010', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (1, 'YON-00011', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (1, 'YON-00012', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (1, 'YON-00013', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (1, 'YON-00014', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (4, 1, N'Giày Cầu LôngGiày cầu lông YonexGiầy cầu lông VictorGiày cầu lông LiningGiày cầu lông VSGiày cầu lông KawasakiGiày Cầu Lông MizunoGiày Cầu Lông KumpooGiày Cầu Lông PromaxGiày cầu lông BabolatGiày Cầu Lông SunbattaXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (2, 'YON-00020', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (2, 'YON-00021', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (2, 'YON-00022', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (2, 'YON-00023', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (2, 'YON-00024', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (4, 1, N'Áo Cầu LôngÁo cầu lông YonexÁo cầu lông VNBÁo cầu lông KamitoÁo cầu lông VSÁo cầu lông VictorÁo cầu lông LiningÁo cầu lông DonexProÁo Cầu Lông Alien ArmourÁo thể thao SFDÁo cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (3, 'YON-00030', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (3, 'YON-00031', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (3, 'YON-00032', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (3, 'YON-00033', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (3, 'YON-00034', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (4, 1, N'Váy cầu lôngVáy cầu lông YonexVáy cầu lông VictecVáy cầu lông LiningVáy cầu lông Donex ProVáy cầu lông VictorVáy cầu lông KamitoVáy cầu lông TaroVáy cầu lông Vina Authentic', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (4, 'YON-00040', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (4, 'YON-00041', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (4, 'YON-00042', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (4, 'YON-00043', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (4, 'YON-00044', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (4, 1, N'Quần Cầu LôngQuần cầu lông YonexQuần cầu lông VictorQuần cầu lông LiningQuần cầu lông VNBQuần Cầu Lông SFDQuần cầu lông Donex ProQuần Cầu Lông ApacsQuần cầu lông Alien ArmourQuần cầu lông MizunoQuần cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (5, 'YON-00050', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (5, 'YON-00051', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (5, 'YON-00052', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (5, 'YON-00053', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (5, 'YON-00054', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (5, 2, N'Vợt Cầu LôngVợt cầu lông YonexVợt cầu lông VictorVợt cầu lông LiningVợt Cầu Lông VSVợt Cầu Lông MizunoVợt cầu lông ApacsVợt Cầu Lông VNBVợt cầu lông ProaceVợt cầu lông ForzaVợt Cầu Lông FlyPowerXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (6, 'LIN-00060', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (6, 'LIN-00061', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (6, 'LIN-00062', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (6, 'LIN-00063', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (6, 'LIN-00064', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (5, 2, N'Giày Cầu LôngGiày cầu lông YonexGiầy cầu lông VictorGiày cầu lông LiningGiày cầu lông VSGiày cầu lông KawasakiGiày Cầu Lông MizunoGiày Cầu Lông KumpooGiày Cầu Lông PromaxGiày cầu lông BabolatGiày Cầu Lông SunbattaXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (7, 'LIN-00070', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (7, 'LIN-00071', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (7, 'LIN-00072', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (7, 'LIN-00073', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (7, 'LIN-00074', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (5, 2, N'Áo Cầu LôngÁo cầu lông YonexÁo cầu lông VNBÁo cầu lông KamitoÁo cầu lông VSÁo cầu lông VictorÁo cầu lông LiningÁo cầu lông DonexProÁo Cầu Lông Alien ArmourÁo thể thao SFDÁo cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (8, 'LIN-00080', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (8, 'LIN-00081', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (8, 'LIN-00082', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (8, 'LIN-00083', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (8, 'LIN-00084', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (5, 2, N'Váy cầu lôngVáy cầu lông YonexVáy cầu lông VictecVáy cầu lông LiningVáy cầu lông Donex ProVáy cầu lông VictorVáy cầu lông KamitoVáy cầu lông TaroVáy cầu lông Vina Authentic', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (9, 'LIN-00090', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (9, 'LIN-00091', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (9, 'LIN-00092', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (9, 'LIN-00093', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (9, 'LIN-00094', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (5, 2, N'Quần Cầu LôngQuần cầu lông YonexQuần cầu lông VictorQuần cầu lông LiningQuần cầu lông VNBQuần Cầu Lông SFDQuần cầu lông Donex ProQuần Cầu Lông ApacsQuần cầu lông Alien ArmourQuần cầu lông MizunoQuần cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (10, 'LIN-00100', N'3UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (10, 'LIN-00101', N'4UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (10, 'LIN-00102', N'5UG4', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (10, 'LIN-00103', N'3UG5', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (10, 'LIN-00104', N'4UG4', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (6, 1, N'Vợt Cầu LôngVợt cầu lông YonexVợt cầu lông VictorVợt cầu lông LiningVợt Cầu Lông VSVợt Cầu Lông MizunoVợt cầu lông ApacsVợt Cầu Lông VNBVợt cầu lông ProaceVợt cầu lông ForzaVợt Cầu Lông FlyPowerXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (11, 'YON-00110', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (11, 'YON-00111', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (11, 'YON-00112', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (11, 'YON-00113', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (11, 'YON-00114', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (6, 1, N'Giày Cầu LôngGiày cầu lông YonexGiầy cầu lông VictorGiày cầu lông LiningGiày cầu lông VSGiày cầu lông KawasakiGiày Cầu Lông MizunoGiày Cầu Lông KumpooGiày Cầu Lông PromaxGiày cầu lông BabolatGiày Cầu Lông SunbattaXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (12, 'YON-00120', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (12, 'YON-00121', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (12, 'YON-00122', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (12, 'YON-00123', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (12, 'YON-00124', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (6, 1, N'Áo Cầu LôngÁo cầu lông YonexÁo cầu lông VNBÁo cầu lông KamitoÁo cầu lông VSÁo cầu lông VictorÁo cầu lông LiningÁo cầu lông DonexProÁo Cầu Lông Alien ArmourÁo thể thao SFDÁo cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (13, 'YON-00130', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (13, 'YON-00131', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (13, 'YON-00132', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (13, 'YON-00133', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (13, 'YON-00134', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (6, 1, N'Váy cầu lôngVáy cầu lông YonexVáy cầu lông VictecVáy cầu lông LiningVáy cầu lông Donex ProVáy cầu lông VictorVáy cầu lông KamitoVáy cầu lông TaroVáy cầu lông Vina Authentic', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (14, 'YON-00140', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (14, 'YON-00141', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (14, 'YON-00142', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (14, 'YON-00143', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (14, 'YON-00144', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (6, 1, N'Quần Cầu LôngQuần cầu lông YonexQuần cầu lông VictorQuần cầu lông LiningQuần cầu lông VNBQuần Cầu Lông SFDQuần cầu lông Donex ProQuần Cầu Lông ApacsQuần cầu lông Alien ArmourQuần cầu lông MizunoQuần cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (15, 'YON-00150', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (15, 'YON-00151', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (15, 'YON-00152', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (15, 'YON-00153', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (15, 'YON-00154', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (7, 3, N'Vợt Cầu LôngVợt cầu lông YonexVợt cầu lông VictorVợt cầu lông LiningVợt Cầu Lông VSVợt Cầu Lông MizunoVợt cầu lông ApacsVợt Cầu Lông VNBVợt cầu lông ProaceVợt cầu lông ForzaVợt Cầu Lông FlyPowerXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (16, 'VIC-00160', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (16, 'VIC-00161', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (16, 'VIC-00162', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (16, 'VIC-00163', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (16, 'VIC-00164', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (7, 3, N'Giày Cầu LôngGiày cầu lông YonexGiầy cầu lông VictorGiày cầu lông LiningGiày cầu lông VSGiày cầu lông KawasakiGiày Cầu Lông MizunoGiày Cầu Lông KumpooGiày Cầu Lông PromaxGiày cầu lông BabolatGiày Cầu Lông SunbattaXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (17, 'VIC-00170', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (17, 'VIC-00171', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (17, 'VIC-00172', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (17, 'VIC-00173', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (17, 'VIC-00174', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (7, 3, N'Áo Cầu LôngÁo cầu lông YonexÁo cầu lông VNBÁo cầu lông KamitoÁo cầu lông VSÁo cầu lông VictorÁo cầu lông LiningÁo cầu lông DonexProÁo Cầu Lông Alien ArmourÁo thể thao SFDÁo cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (18, 'VIC-00180', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (18, 'VIC-00181', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (18, 'VIC-00182', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (18, 'VIC-00183', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (18, 'VIC-00184', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (7, 3, N'Váy cầu lôngVáy cầu lông YonexVáy cầu lông VictecVáy cầu lông LiningVáy cầu lông Donex ProVáy cầu lông VictorVáy cầu lông KamitoVáy cầu lông TaroVáy cầu lông Vina Authentic', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (19, 'VIC-00190', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (19, 'VIC-00191', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (19, 'VIC-00192', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (19, 'VIC-00193', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (19, 'VIC-00194', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (7, 3, N'Quần Cầu LôngQuần cầu lông YonexQuần cầu lông VictorQuần cầu lông LiningQuần cầu lông VNBQuần Cầu Lông SFDQuần cầu lông Donex ProQuần Cầu Lông ApacsQuần cầu lông Alien ArmourQuần cầu lông MizunoQuần cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (20, 'VIC-00200', N'Size 39', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (20, 'VIC-00201', N'Size 40', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (20, 'VIC-00202', N'Size 41', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (20, 'VIC-00203', N'Size 42', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (20, 'VIC-00204', N'Size 43', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (8, 1, N'Vợt Cầu LôngVợt cầu lông YonexVợt cầu lông VictorVợt cầu lông LiningVợt Cầu Lông VSVợt Cầu Lông MizunoVợt cầu lông ApacsVợt Cầu Lông VNBVợt cầu lông ProaceVợt cầu lông ForzaVợt Cầu Lông FlyPowerXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (21, 'YON-00210', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (21, 'YON-00211', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (21, 'YON-00212', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (21, 'YON-00213', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (21, 'YON-00214', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (8, 1, N'Giày Cầu LôngGiày cầu lông YonexGiầy cầu lông VictorGiày cầu lông LiningGiày cầu lông VSGiày cầu lông KawasakiGiày Cầu Lông MizunoGiày Cầu Lông KumpooGiày Cầu Lông PromaxGiày cầu lông BabolatGiày Cầu Lông SunbattaXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (22, 'YON-00220', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (22, 'YON-00221', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (22, 'YON-00222', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (22, 'YON-00223', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (22, 'YON-00224', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (8, 1, N'Áo Cầu LôngÁo cầu lông YonexÁo cầu lông VNBÁo cầu lông KamitoÁo cầu lông VSÁo cầu lông VictorÁo cầu lông LiningÁo cầu lông DonexProÁo Cầu Lông Alien ArmourÁo thể thao SFDÁo cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (23, 'YON-00230', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (23, 'YON-00231', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (23, 'YON-00232', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (23, 'YON-00233', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (23, 'YON-00234', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (8, 1, N'Váy cầu lôngVáy cầu lông YonexVáy cầu lông VictecVáy cầu lông LiningVáy cầu lông Donex ProVáy cầu lông VictorVáy cầu lông KamitoVáy cầu lông TaroVáy cầu lông Vina Authentic', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (24, 'YON-00240', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (24, 'YON-00241', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (24, 'YON-00242', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (24, 'YON-00243', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (24, 'YON-00244', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (8, 1, N'Quần Cầu LôngQuần cầu lông YonexQuần cầu lông VictorQuần cầu lông LiningQuần cầu lông VNBQuần Cầu Lông SFDQuần cầu lông Donex ProQuần Cầu Lông ApacsQuần cầu lông Alien ArmourQuần cầu lông MizunoQuần cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (25, 'YON-00250', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (25, 'YON-00251', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (25, 'YON-00252', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (25, 'YON-00253', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (25, 'YON-00254', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (9, 2, N'Vợt Cầu LôngVợt cầu lông YonexVợt cầu lông VictorVợt cầu lông LiningVợt Cầu Lông VSVợt Cầu Lông MizunoVợt cầu lông ApacsVợt Cầu Lông VNBVợt cầu lông ProaceVợt cầu lông ForzaVợt Cầu Lông FlyPowerXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (26, 'LIN-00260', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (26, 'LIN-00261', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (26, 'LIN-00262', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (26, 'LIN-00263', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (26, 'LIN-00264', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (9, 2, N'Giày Cầu LôngGiày cầu lông YonexGiầy cầu lông VictorGiày cầu lông LiningGiày cầu lông VSGiày cầu lông KawasakiGiày Cầu Lông MizunoGiày Cầu Lông KumpooGiày Cầu Lông PromaxGiày cầu lông BabolatGiày Cầu Lông SunbattaXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (27, 'LIN-00270', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (27, 'LIN-00271', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (27, 'LIN-00272', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (27, 'LIN-00273', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (27, 'LIN-00274', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (9, 2, N'Áo Cầu LôngÁo cầu lông YonexÁo cầu lông VNBÁo cầu lông KamitoÁo cầu lông VSÁo cầu lông VictorÁo cầu lông LiningÁo cầu lông DonexProÁo Cầu Lông Alien ArmourÁo thể thao SFDÁo cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (28, 'LIN-00280', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (28, 'LIN-00281', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (28, 'LIN-00282', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (28, 'LIN-00283', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (28, 'LIN-00284', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (9, 2, N'Váy cầu lôngVáy cầu lông YonexVáy cầu lông VictecVáy cầu lông LiningVáy cầu lông Donex ProVáy cầu lông VictorVáy cầu lông KamitoVáy cầu lông TaroVáy cầu lông Vina Authentic', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (29, 'LIN-00290', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (29, 'LIN-00291', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (29, 'LIN-00292', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (29, 'LIN-00293', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (29, 'LIN-00294', N'Size XXL', 1000000, NULL, 1);
INSERT INTO dbo.Product (CategoryId, BrandId, Name, Description, ImageUrl, IsActive) VALUES (9, 2, N'Quần Cầu LôngQuần cầu lông YonexQuần cầu lông VictorQuần cầu lông LiningQuần cầu lông VNBQuần Cầu Lông SFDQuần cầu lông Donex ProQuần Cầu Lông ApacsQuần cầu lông Alien ArmourQuần cầu lông MizunoQuần cầu lông KawasakiXem thêm', NULL, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (30, 'LIN-00300', N'Size S', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (30, 'LIN-00301', N'Size M', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (30, 'LIN-00302', N'Size L', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (30, 'LIN-00303', N'Size XL', 1000000, NULL, 1);
INSERT INTO dbo.ProductVariant (ProductId, SKU, VariantName, Price, ImageUrl, IsActive) VALUES (30, 'LIN-00304', N'Size XXL', 1000000, NULL, 1);
GO
